name: fast_food_cafe_grill
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intro_slider: ^4.2.0
  carousel_slider: ^4.0.0
  provider: ^6.0.1
  curved_nav_bar: ^0.0.2
  flutter_image_slideshow: ^0.1.2
  firebase_core: ^1.13.1
  firebase_database: ^9.0.4
  firebase_storage: ^10.2.4
  firebase_core_web: ^1.6.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.20
  intl: ^0.17.0
  image_picker: ^0.8.4+11
  google_maps_flutter: ^2.1.6 
  shared_preferences: ^2.0.15
  shared_preferences_web: ^2.0.4
  contactus: ^1.2.0
 
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  geocoding: ^2.0.4
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

 
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-Regular.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
